import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import firebase from "firebase/app";
import { useRouter } from "next/router";
import initFirebase from "../services/firebase.js";
import "firebase/auth";
import { useState, useEffect } from "react";

initFirebase();
export default function Home() {
  const router = useRouter();
  firebase.auth().onAuthStateChanged(function (user) {
    if (user) {
      router.push("/dashboard");
    }
  });
  console.log("no user");
  return (
    <div>
      <Head>
        <title>Babtiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1
          style={{ fontSize: "60px", fontWeight: "bold", lineHeight: "150%" }}
        >
          Babitz
        </h1>

        <p style={{ fontSize: "30px", lineHeight: "150%" }}>
          Order, Eat, Repeat
        </p>
        <Link href="/login" passHref>
          <button type="button" className="btn btn-primary">
            Start
          </button>
        </Link>
      </main>
    </div>
  );
}
